# Generated by Django 4.2.4 on 2023-11-24 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=50)),
                ('año', models.CharField(max_length=200)),
                ('gama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=200)),
                ('año', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='media/')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='certamen3App.marca')),
            ],
        ),
    ]
